### PR TITLE
Update builtin version of ical.js

### LINKED ISSUE #63: Recurring (google calendar) events shown 1 day earlier
Recurring (google calendar) events shown 1 day earlier.

### PR DESCRIPTION
**Pull request by jerome-pouiller**
The built-in version of ical.js has several bugs.

Fix https://github.com/heskja/MMM-CalendarWeek/issues/63

### CODE REVIEW

**Comment by jerome-pouiller** [comment]
Wait, I have sent my PR too quickly.

**Comment by dberntsson** [comment]
I got this by just git pulling

`[25.11.2023 19:08.01.480] [ERROR] (node:23812) UnhandledPromiseRejectionWarning: Error: Cannot find module './vendor/ical.js'
Require stack:
- /home/pi/MagicMirror_modules/MMM-CalendarWeek/calendarfetcher.js
- /home/pi/MagicMirror_modules/MMM-CalendarWeek/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at node:internal/modules/cjs/loader:1084:15
    at Function.<anonymous> (node:electron/js2c/browser_init:2:117419)
    at Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
    at node:internal/modules/cjs/loader:929:27
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/home/pi/MagicMirror_modules/MMM-CalendarWeek/calendarfetcher.js:8:12)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Object..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/home/pi/MagicMirror_modules/MMM-CalendarWeek/node_helper.js:10:23)
(Use `electron --trace-warnings ...` to show where the warning was created)
[25.11.2023 19:08.01.482] [ERROR] (node:23812) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)`

**Comment by dberntsson** [comment]
Could have been due to some other instructions to remove ./vendor/ical.js

With that restored, new error occurred

`[25.11.2023 19:53.09.351] [ERROR] (node:24269) UnhandledPromiseRejectionWarning: Error: Cannot find module 'rrule'
Require stack:
- /home/pi/MagicMirror_modules/MMM-CalendarWeek/vendor/ical.js/node-ical.js
- /home/pi/MagicMirror_modules/MMM-CalendarWeek/vendor/ical.js/index.js
- /home/pi/MagicMirror_modules/MMM-CalendarWeek/calendarfetcher.js
- /home/pi/MagicMirror_modules/MMM-CalendarWeek/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at node:internal/modules/cjs/loader:1084:15
    at Function.<anonymous> (node:electron/js2c/browser_init:2:117419)
    at Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
    at node:internal/modules/cjs/loader:929:27
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/home/pi/MagicMirror_modules/MMM-CalendarWeek/vendor/ical.js/node-ical.js:27:13)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Object..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/home/pi/MagicMirror_modules/MMM-CalendarWeek/vendor/ical.js/index.js:3:12)
(Use `electron --trace-warnings ...` to show where the warning was created)
[25.11.2023 19:53.09.352] [ERROR] (node:24269) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)`

**Comment by dberntsson** [comment]
Adding 
+        "rrule":"^2.7.1",
to package.json solved it. New PR on the way.

**Comment by jerome-pouiller** [comment]
Hello @dberntsson,

I have checked my setup. My `package.json` still mention `rrule-alt`:

```
$ cat package.json
{
    "dependencies": {
        "valid-url": "^1.0.9",
        "request":"^2.88.2",
        "rrule-alt":"^2.2.8",
        "moment":"^2.29.4"
    }
}
```

However,  `rrule-alt` seems obsolete and `rrule` is recommended. Anyway, it seems you find the problem.

Do you observe the issue with the hour shift mentionned in https://github.com/heskja/MMM-CalendarWeek/issues/63 ?

**Comment by dberntsson** [comment]
What I noticed is that my calendar events are 1 hour off.
I live in UTC+1 and calendar seems to show UTC.
Seen something similar?

**Pull request merged**
